    % The feature viewer visualizes features for the currently selected 
    % datapoints. It can also depict the local graph of the currently selected datapoint.
    % which is helpful when exploring embeddings such as those generated by t-SNE or UMAP or other
    % large scale visualizations.
    %
    % Below a neighborhood of some datapoint in the MNIST example dataset is displayed (left). On the right
    % the feature vector of the currently selected datapoint is displayed.
    %
    % DSPACE-HELP-IMAGE<CoordinateViewer_img1_v2.png>
    %
    % <h3>Mouse and Keyboard Controls</h3>
    % The text in the bottom left corner depicts the name of the currenttly selected features.
    % The selected features can be changed by right clicking on the name and selecting from the
    % context menu that will come up.
    % 
    % The first two toolbar buttons bring up the settings dialog and visibility context menu. 
    % The third button switches between using an explicit neighborhood or the one implied by the current
    % ordering variable (advanced function). The fourth button allows to define a feature cutout
    % (a selection inside the feature vector). 
    % 
    % The fifth button plays back the current 1 dimensional signal 
    % as a .wav file at a sampling rate of 32kHz (experimental). 
    %
    % <h3>Editing Feature Settings</h3>
    % Some features have internal settings that can be changed. For those features,
    % checking the option 'Attempt to Edit Feature Settings after Closing' in the settings dialog 
    % (first toolbar button) will bring up the feature settings window. Changes can be propagated to all
    % datasources in the current level.
    %
    %
    % 
    %
    %<PRE>
    % This file is part of dspace-GUI.
    % 
    % Copyright (C) 2020 University Zurich, Sepp Kollmorgen
    % 
    % dspace-GUI is licenced under a custom license (see LICENSE file).
    % 
    % This program is distributed in the hope that it will be useful,
    % but WITHOUT ANY WARRANTY; without even the implied warranty of
    % MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    % </PRE>
    % <b>Dataspace on Github</b>: <a href="matlab:web('https://github.com/skollmor/dspace', '-browser')">https://github.com/skollmor/dspace</a>

