function [ moduleFcns ] = define_modulefcns( )
    % Do not edit this file.
    %
    % Note: To add custom module functions, you should edit the file dataspaceExtensions_defineModuleFunctions().
    %
    % <a href="matlab:edit dataspaceExtensions_defineModuleFunctions">Edit dataspaceExtensions_defineModuleFunctions</a>
    %
    %
    % 
    %
    %<PRE>
    % This file is part of dspace-core.
    %
    % Copyright (C) 2020 University Zurich, Sepp Kollmorgen
    %
    % This program is free software: you can redistribute it and/or modify
    % it under the terms of the GNU Affero General Public License as published by
    % the Free Software Foundation, either version 3 of the License, or
    % (at your option) any later version.
    %
    % This program is distributed in the hope that it will be useful,
    % but WITHOUT ANY WARRANTY; without even the implied warranty of
    % MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    % GNU Affero General Public License for more details.
    %
    % You should have received a copy of the GNU Affero General Public License
    % along with this program (see LICENSE file).  If not, see <https://www.gnu.org/licenses/>.
    % </PRE>
    % <b>Dataspace on Github</b>: <a href="matlab:web('https://github.com/skollmor/dspace', '-browser')">https://github.com/skollmor/dspace</a>

    
    % Standard Dataspace Module Fcns:
    moduleFcns = {...
        % Essentials
        @dspacefcns.Essentials.binningTool
        @dspacefcns.Essentials.samplingTool
        @dspacefcns.Essentials.deleteLabels
        @dspacefcns.Essentials.deleteFeatures
        @dspacefcns.Essentials.deleteGraphs
        @dspacefcns.Essentials.labelDatapoints
        @dspacefcns.Essentials.runMatlabFunction
        @dspacefcns.Essentials.collapseSources
        @dspacefcns.Essentials.deleteDatasources
        @dspacefcns.Essentials.createSequenceVariable
        @dspacefcns.Essentials.applySequenceTransform
        %--LGs
        @dspacefcns.Graphs.localOutlierFactor
        @dspacefcns.Graphs.computeMixingHistograms
        %@dspacefcns.Graphs.computeMixingMatrix
        %@dspacefcns.Graphs.computeMixingMatrix_v2
        @dspacefcns.Graphs.computeMixingMatrix_v3
        %@dspacefcns.Graphs.createHighDLocalGroup
        %@dspacefcns.Graphs.createHighDLocalGroup_v2
        @dspacefcns.Graphs.createHighDLocalGroup_v3
        @dspacefcns.Graphs.localGroupToVariable
        @dspacefcns.Graphs.graphDomainToLabel
        %@dspacefcns.Graphs.localGroupAnalysis1D
        @dspacefcns.Graphs.localGroupAnalysis1D_v2
        %@dspacefcns.Graphs.localGroupAnalysisND
        @dspacefcns.Graphs.localGroupAnalysisND_v2
        @dspacefcns.Graphs.create2DLocalGroup
        @dspacefcns.Graphs.computeLGaccumulatorOnSelection
        %--Clustering
        @dspacefcns.Clustering.kmeansOnCurrentSelection
        @dspacefcns.Clustering.affinityPropagationOnCurrentSelection
        @dspacefcns.Clustering.linkageClusteringOnSelection
        @dspacefcns.Clustering.computeClusteringSilhouette
        @dspacefcns.Clustering.DBScanOnCurrentSelection
        %--Prediction
        @dspacefcns.Prediction.linearRegression
        @dspacefcns.Prediction.linearRegression_v2
        @dspacefcns.Prediction.nnClassifier
        %--Coordinate Operations
        @dspacefcns.Features.createFeaturesFromLabels
        @dspacefcns.Features.embedCurrentSelection
        @dspacefcns.Features.tsneOnCurrentSelection
        @dspacefcns.Features.createCutoutCoordinates
        @dspacefcns.Features.normalizeFeatures
        @dspacefcns.Features.pcaOnCurrentSelection
        @dspacefcns.Features.localPcaOnCurrentSelection
        @dspacefcns.Features.reorderChannels
        @dspacefcns.Features.fftOnCurrentSelection
        @dspacefcns.Features.freezeFeatures
        @dspacefcns.Features.createLabelsFromFeatures
        @dspacefcns.Features.createSmoothedDerivedCoordinates_v2
        @dspacefcns.Features.createStackedDerivedCoordinates
        @dspacefcns.Features.faOnCurrentSelection
        @dspacefcns.Features.createShuffledCoordinates
        @dspacefcns.Features.createImageResizingCoordinates
        %--Various
        @dspacefcns.createDataviews
        @dspacefcns.crossCorrelateOnSelection
        @dspacefcns.deleteDatapoints
        @dspacefcns.reorderDatapoints
        @dspacefcns.Tensorflow.create_DLC_scoremapCoordinates 
        }';
       
end
